### ISSUE TITLE
Target temperature bouncing

### ISSUE THREAD

**Issue by jaythomas** [HestiaPi/hestia-touch-one-ui#11]
I'm surprised I haven't seen anyone mention this issue yet, but if you tap to change the temperature multiple times in quick succession, openhab will receive the temperature change from the first request and relay it back to the frontend and cause the temperature to bounce back.

For example:
- Temperature is 70.
- Increment to 71... increment to 72...
- OpenHab receives 71 and sends this temperature back to the frontend
- The screen shows the temperature bounce from 72 backwards to 71

In some cases I've even seen it bounce between 71<->72 stuck in an infinite loop.

@gulliverrr I'd like to hear your thoughts on how to handle this, but two solutions I see that could fix this:
1. Implement a **debounce** on the [decrement/increment](https://github.com/HestiaPi/hestia-touch-one-ui/blob/869925e1321f1fd47277d1290cfd30b71d45601a/src/plugins/store.js#L340-L356) functions so that tapping the screen many times in a row only sends one event to OpenHab
2. On the OpenHab side when sending the event to change the temperature, also send an ID of the client the message originated from. If the client sees the ID of origin is itself it knows to ignore the message.

**Comment by gulliverrr** [comment]
I'm inclined to go for 1. A simple timer (1sec?) to delay dispatching updates I believe would be long enough to stop bouncing.
