### ISSUE TITLE
Cooling is not changed to active if triggered externally

### ISSUE THREAD

**Issue by gulliverrr** [HestiaPi/hestia-touch-one-ui#6]
Previous state:
Cooling is not active/selected on the UI and is turned on from outside the LCD
Expected behaviour:
Cooling should appear as active/selected on the UI
Actual behaviour:
Active/selected screen does not change. Cooling animation starts (as long as setpoint is lower than current)
Bug is not present for heating, fan, humidity or hot water.

**Comment by jaythomas** [comment]
Please verify if this is fixed by #8.

**Comment by gulliverrr** [comment]
Seems fixed by #8. Will auto close once merged.
