### ISSUE TITLE
Feature's current state not shown

### ISSUE THREAD

**Issue by gulliverrr** [HestiaPi/hestia-touch-one-ui#7]
Unless a feature is currently running (animating icon) there is no way to tell the current state (AUTO/OFF/Boost) from the LCD

**Comment by jaythomas** [comment]
The power settings modal could display an asterisk by the option selected to show which one is selected, but that would mean you need to open the modal first to see it.
If you want to see the current power setting available on the screen at all times there is room at the bottom (maybe bottom left) next to the boost timer message.
Let me know what you think and I'll try to implement that.

**Comment by gulliverrr** [comment]
Why not reusing the same area for both boost countdown and active mode and maybe move it from right to the center or left at the bottom (status) line?

**Comment by jaythomas** [comment]
Yup, I think we're on the same page.

**Comment by gulliverrr** [comment]
Seems fixed by #8. Will auto close once merged.
